# Generated by Django 5.0.3 on 2024-03-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_dealrequest_created_at_dealrequest_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='city_district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='real_estate.citydistrict'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='metro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='real_estate.metro'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='title_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
    ]
