# Generated by Django 5.0.3 on 2024-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_realestate_city_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydistrict',
            name='city_district',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metro',
            name='metro_station',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='title_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
